version: 1.0.{build}
image: Visual Studio 2017
nuget:
  account_feed: true
install:
- cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
before_build:
- cmd: nuget restore
build:
